name = "rankings-trade-cron"
main = "./worker/cron.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/15 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "rankings-trade-prod"
database_id = "03f54a17-4210-412b-9d9b-641078b31a8c"
