name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: antfu/changelogithub@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
